version: "3.7"


services:
    web:
        container_name: auth-service
        build: .
        ports:
            - "8050:8083"
        restart: always
        environment:
            - DB_SERVICE_IP=172.20.18.91
            - DB_SERVICE_PORT=8034
