version: "3.7"


services:
    web:
        container_name: auth_service
        build: .
        ports:
            - "60004:60004"
        restart: always
        environment:
            - DB_SERVICE_IP=77.240.38.184
            - DB_SERVICE_PORT=60002

    redis:
        image: redis:latest
        expose:
            - 6379
        ports:
            - "6379:6379"
        restart: "always"
